version: '3'

services:

# Server
  server: 
    build: "./cs411_backend"
    environment:
        SERVER_PORT: ${SERVER_PORT}
        NEO4J_Credentials: ${NEO4J_Credentials}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_HOST: ${MYSQL_HOST}
        WAIT_HOSTS: neo4j:7687, mysql:3306
    ports:
        - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
        - ./cs411_backend/src:/srv/app/backend/src
    links: 
       - "mysql:mysql"
       - "neo4j: neo4j"
# Client

  client:
    build: "./cs411_frontend"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    ports:
        - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./cs411_frontend/src:/srv/app/frontend/src
# MYSQL
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./import:/var/lib/mysql-files/

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_Credentials}
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
    volumes:
      - ./db/dbms:/data/dbms
      - ./import:/var/lib/neo4j/import
      - ./plugins:/var/lib/neo4j/plugins
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
volumes:
  my-db:
