version: '3'

services:

# Server
  server: 
    build: "./cs411_backend"
    environment:
        SERVER_PORT: ${SERVER_PORT}
    ports:
        - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
        - ./cs411_backend/src:/srv/app/backend/src
    command: npm start

# Client

  client:
    build: "./cs411_frontend"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    ports:
        - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./cs411_frontend/src:/srv/app/frontend/src
    command: npm start
# MYSQL
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_Credentials}
    volumes:
      - ./db/dbms:/data/dbms
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
volumes:
  my-db:
